name: Update Filters

on:
  schedule:
    # Run this workflow every day at 00:00 UTC.
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run update-filters.sh
        run: ./update-filters.sh

      - name: Update filters.dat
        uses: EndBug/add-and-commit@v7
        with:
          branch: master
          default_author: github_actions
          message: 'Update filters.dat'
          pull_strategy: 'NO-PULL'
          push: true
          signoff: true
